/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * 在主包某窗（hwnd，由主库 getActiveHost().getNativeHandle() 取得）上贴一块 WebView2（Chromium）子面，
 * 加载远程/本地 URL，区域为相对该窗客户区的物理像素矩形 (x, y, width, height)，返回 view id（u32）。
 *
 * url：远程 `http(s)://…` 原样加载；本地文件路径（相对 process.cwd() 或绝对，含 `file://`）经自定义协议
 * 以 http://flux.localhost/… 加载（同目录相对资源可加载、桥与生命周期可用）。
 * on_event：原生回抛通道（首参 error，值在第二参，JSON 字符串）。事件 type：
 *   'domready' | 'loaded' | 'navigate'（主框导航，带 url）| 'closed'（closeView 时）
 *   | 'ipc'（页面 fluxBridge.post/request，request 带 requestId）| 'newwindow'（被抑制的开新窗请求）。
 */
export declare function createView(hwnd: number, x: number, y: number, width: number, height: number, url: string, onEvent: (...args: any[]) => any): number
/**
 * 同 create_view，但内容是一段【内联 HTML 字符串】。经自定义协议以 http://flux.localhost 提供，
 * 因此内联页同样可用双向桥与生命周期（相对资源按协议根解析）。
 */
export declare function createViewHtml(hwnd: number, x: number, y: number, width: number, height: number, html: string, onEvent: (...args: any[]) => any): number
/** 让某块 view 原地导航（远程 http(s) 原样；本地路径/file:// 经协议转换）。 */
export declare function navigate(id: number, url: string): void
/** 让某块 view 加载一段内联 HTML（覆写该 id 的协议内容并触发重载）。 */
export declare function loadHtml(id: number, html: string): void
/** 让某块 view 打开本地文件（path 传相对 process.cwd() 或绝对路径；经协议加载，同目录相对资源可用）。 */
export declare function openFile(id: number, path: string): void
/** 改某块 view 的区域（父窗 resize / 面板重排时同步；物理像素矩形）。同时记下真实区域供 set_visible 恢复。 */
export declare function setBounds(id: number, x: number, y: number, width: number, height: number): void
/**
 * 显隐某块 view（airspace 用）：WebView2 是主窗的 WS_CHILD 子面，永远画在 Skia 之上，Skia 浮层（抽屉/弹窗）盖不住它。
 * 需要让浮层压住网页时，先把子面移到屏外（负坐标，被父窗客户区裁掉）隐藏，浮层关闭后再恢复到真实区域。
 */
export declare function setVisible(id: number, visible: boolean): void
/**
 * 宿主(RN) → 网页：把 message（JSON 字符串；非合法 JSON 则按字符串处理）投递到页面
 * window.onFluxMessage / fluxBridge.onMessage。页面就绪前会排队，loaded 后冲刷。
 */
export declare function postMessage(id: number, message: string): void
/** 逃生口：在某块 view 里直接执行任意 JS（不做封装；用于高级交互/取值）。 */
export declare function evalJs(id: number, script: string): void
/** 摘除一块 view：清内联暂存 → 回抛 {type:'closed'} → drop WebView（Chromium 子面随之销毁）。 */
export declare function closeView(id: number): boolean
/**
 * 宿主(RN) → 网页（应答）：回应页面 `fluxBridge.request(obj)` 发起的请求——按 requestId 落地
 * 页面 `window.__fluxReply(rid, result)`，使页面侧 Promise resolve。result 传 JSON 字符串（非合法 JSON 按字符串处理）。
 */
export declare function postReply(id: number, requestId: string, result: string): void
/**
 * RN → 网页（带返回值）：在该 view 内执行 JS，并把「求值结果」异步回抛（wry evaluate_script_with_callback）。
 * on_result(err, jsonValue)：jsonValue 为求值结果序列化成的 JSON 串（无返回值/异常时为 `"null"`）。
 * 区别于 evalJs（fire-and-forget 逃生口），此函数可读回 document.title、调页面函数取返回值等。
 */
export declare function evalJsResult(id: number, script: string, onResult: (...args: any[]) => any): void
/** 取某块 view 当前地址（WebView2 实时 URL）。 */
export declare function getViewUrl(id: number): string
